export class MeshGenerator {
  /**
   * Generates a watertight binary STL from a height map.
   * Coordinate system: X = width, Y = height (depth), Z = up.
   */
  generate(heights, gridW, gridH, physicalW, physicalH) {
    const dx = physicalW / (gridW - 1);
    const dy = physicalH / (gridH - 1);

    const topTris  = 2 * (gridW - 1) * (gridH - 1);
    const botTris  = 2; // flat bottom = one rectangle
    const sideTris = 4 * (gridW + gridH - 2);
    const total    = topTris + botTris + sideTris;

    const buf  = new ArrayBuffer(80 + 4 + total * 50);
    const view = new DataView(buf);

    // ASCII header
    const hdr = 'Generated by Image to 3D';
    for (let i = 0; i < hdr.length && i < 80; i++) view.setUint8(i, hdr.charCodeAt(i));
    view.setUint32(80, total, true);

    let off = 84;

    const flt = (v) => { view.setFloat32(off, v, true); off += 4; };
    const u16 = ()  => { view.setUint16(off, 0,  true); off += 2; };

    const vec = (x, y, z) => { flt(x); flt(y); flt(z); };

    const tri = (nx, ny, nz, ax, ay, az, bx, by, bz, cx, cy, cz) => {
      vec(nx, ny, nz);
      vec(ax, ay, az);
      vec(bx, by, bz);
      vec(cx, cy, cz);
      u16();
    };

    const norm = (ax, ay, az, bx, by, bz, cx, cy, cz) => {
      const ux = bx-ax, uy = by-ay, uz = bz-az;
      const vx = cx-ax, vy = cy-ay, vz = cz-az;
      const nx = uy*vz - uz*vy;
      const ny = uz*vx - ux*vz;
      const nz = ux*vy - uy*vx;
      const len = Math.sqrt(nx*nx + ny*ny + nz*nz) || 1;
      return [nx/len, ny/len, nz/len];
    };

    const h = (xi, yi) => Math.max(0.001, heights[yi * gridW + xi]);

    // ── Top surface ───────────────────────────────────────────────────────────
    for (let yi = 0; yi < gridH - 1; yi++) {
      for (let xi = 0; xi < gridW - 1; xi++) {
        const x0 = xi*dx,       y0 = yi*dy;
        const x1 = (xi+1)*dx,   y1 = (yi+1)*dy;
        const h00 = h(xi,yi),   h10 = h(xi+1,yi);
        const h01 = h(xi,yi+1), h11 = h(xi+1,yi+1);

        let [nx,ny,nz] = norm(x0,y0,h00, x1,y0,h10, x1,y1,h11);
        tri(nx,ny,nz, x0,y0,h00, x1,y0,h10, x1,y1,h11);

        [nx,ny,nz] = norm(x0,y0,h00, x1,y1,h11, x0,y1,h01);
        tri(nx,ny,nz, x0,y0,h00, x1,y1,h11, x0,y1,h01);
      }
    }

    // ── Bottom surface (flat, normal = -Z) ────────────────────────────────────
    // The bottom is a single flat rectangle, so two triangles suffice instead of a
    // full grid. Its edges are coplanar with the side-wall bottoms at z=0, so the
    // resulting T-junctions don't affect any slice plane above z=0.
    {
      const X = (gridW - 1) * dx, Y = (gridH - 1) * dy;
      tri(0,0,-1, 0,0,0, X,Y,0, X,0,0);
      tri(0,0,-1, 0,0,0, 0,Y,0, X,Y,0);
    }

    // ── Front wall (yi=0, normal = -Y) ────────────────────────────────────────
    for (let xi = 0; xi < gridW - 1; xi++) {
      const x0=xi*dx, x1=(xi+1)*dx, h0=h(xi,0), h1=h(xi+1,0);
      tri(0,-1,0, x0,0,0, x1,0,0, x1,0,h1);
      tri(0,-1,0, x0,0,0, x1,0,h1, x0,0,h0);
    }

    // ── Back wall (yi=gridH-1, normal = +Y) ───────────────────────────────────
    for (let xi = 0; xi < gridW - 1; xi++) {
      const x0=xi*dx, x1=(xi+1)*dx, yb=(gridH-1)*dy;
      const h0=h(xi,gridH-1), h1=h(xi+1,gridH-1);
      tri(0,1,0, x0,yb,h0, x1,yb,h1, x1,yb,0);
      tri(0,1,0, x0,yb,h0, x1,yb,0,  x0,yb,0);
    }

    // ── Left wall (xi=0, normal = -X) ─────────────────────────────────────────
    for (let yi = 0; yi < gridH - 1; yi++) {
      const y0=yi*dy, y1=(yi+1)*dy, h0=h(0,yi), h1=h(0,yi+1);
      tri(-1,0,0, 0,y0,0, 0,y0,h0, 0,y1,h1);
      tri(-1,0,0, 0,y0,0, 0,y1,h1, 0,y1,0);
    }

    // ── Right wall (xi=gridW-1, normal = +X) ──────────────────────────────────
    for (let yi = 0; yi < gridH - 1; yi++) {
      const xr=(gridW-1)*dx, y0=yi*dy, y1=(yi+1)*dy;
      const h0=h(gridW-1,yi), h1=h(gridW-1,yi+1);
      tri(1,0,0, xr,y0,0, xr,y1,h1, xr,y0,h0);
      tri(1,0,0, xr,y0,0, xr,y1,0,  xr,y1,h1);
    }

    return buf;
  }

  download(buf, filename = 'image3d.stl') {
    const blob = new Blob([buf], { type: 'application/octet-stream' });
    const url  = URL.createObjectURL(blob);
    const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
    a.click();
    URL.revokeObjectURL(url);
  }
}
